### ISSUE TITLE
Feedback Openshift Hands On Lab

### ISSUE THREAD

**Issue by paulherbosch** [snowdrop/cloud-native-lab#13]
Hi,

- remove the parts where people need to write code. have them edit existing files to change some properties.

- try to focus less on java/maven. people not familiar to this ecosystem are clueless.

- explain different openshift components and/or the openshift platform more in depth, before beginning the lab.

thx, Paul

**Comment by cmoulliard** [comment]
> openshift platform more in depth, before beginning the lab

Great idea. Next time, we should certainlyt include a 1h training around openshift prior to do the lab.

> less on java/maven

This is always a challenge to know who will participate to such events and skills of the students

> remove the parts where people need to write code. have them edit existing files to change some properties.

ok

**Comment by fvanraem** [comment]
> remove the parts where people need to write code. have them edit existing files to change some properties.  

Agreed. This takes time and does not add much to the actual Openshift topic at hand.
Maybe prepare some files (not an entire project) that can be dropped into the project created by the launcher.

One thing that I would like to have explained better is how to do the things we did but with a pre-existing application.

Thx, Filip

**Comment by cmoulliard** [comment]
> with a pre-existing application.

For existing applications, 2 approaches are possible : 
- Add Fabric8 Maven Plugin to your pom project, be authenticated with an existing openshift cluster and then run `mvn fabric8:deploy`
- Create your own `openshift template` and then create an application using these commands `oc new-app -f openshift/cloud-native-demo_backend_template.yml` and `oc start-build cloud-native-backend-s2i --from-dir=. --follow`
